commit 10

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -321,29 +321,29 @@ jobs:
               '
 
     - name: Get Grafana URL
-      id: grafana-url
-      run: |        
-            EC2_IP=${{ needs.Deploy_CloudFormation.outputs.ec2_ip }}
-            GRAFANA_URL=$(ssh -i jenkins.pem -o StrictHostKeyChecking=no ubuntu@$EC2_IP '
-            GRAFANA_SERVICE=$(kubectl get services -n prometheus -l "app.kubernetes.io/name=grafana" -o jsonpath="{.items[0].metadata.name}")
-            if [ -z "$GRAFANA_SERVICE" ]; then
-              echo "Grafana service not found."
-              exit 1
-            fi
-        
-            # Obtener la URL del servicio de Grafana
-            kubectl get service $GRAFANA_SERVICE -n prometheus -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"
+      id: grafana-url      
+      run: |           
+            EC2_IP=${{ needs.Deploy_CloudFormation.outputs.ec2_ip }}            
+            GRAFANA_URL=$(ssh -i jenkins.pem -o StrictHostKeyChecking=no ubuntu@$EC2_IP '         
+            GRAFANA_SERVICE=$(kubectl get services -n prometheus -l "app.kubernetes.io/name=grafana" -o jsonpath="{.items[0].metadata.name}")           
+              if [ -z "$GRAFANA_SERVICE" ]; then            
+                  echo "Grafana service not found."            
+                  exit 1            
+              fi
+                       
+            # Obtener la URL del servicio de Grafana           
+            kubectl get service $GRAFANA_SERVICE -n prometheus -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"                                
             ')
-        
-            # Verificar si se obtuvo la URL correctamente
-            if [ -z "$GRAFANA_URL" ]; then
-              echo "Failed to get Grafana URL"
-              exit 1
-            fi
-        
-            # Guardar la URL de Grafana en el output
-            echo "grafana_url=http://${GRAFANA_URL}" >> $GITHUB_OUTPUT
-            echo "Grafana URL: http://${GRAFANA_URL}
+            
+            # Verificar si se obtuvo la URL correctamente            
+              if [ -z "$GRAFANA_URL" ]; then           
+                echo "Failed to get Grafana URL"            
+                exit 1           
+              fi
+                      
+              # Guardar la URL de Grafana en el output           
+              echo "grafana_url=http://${GRAFANA_URL}" >> $GITHUB_OUTPUT            
+              echo "Grafana URL: http://${GRAFANA_URL}"            
 
   Create_Connection_Info:
     needs: [Deploy_CloudFormation, Deploy_Nginx, Deploy_EFK, Conexion_EC2, Deploy_Monitoring]
