commit 6

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -240,7 +240,6 @@ jobs:
     needs: [Deploy_CloudFormation, Conexion_EC2]
     runs-on: ubuntu-latest
     outputs:
-      prometheus_url: ${{ steps.prometheus-url.outputs.prometheus_url }}
       grafana_url: ${{ steps.grafana-url.outputs.grafana_url }}
     steps:
     - name: Checkout code
@@ -292,96 +291,59 @@ jobs:
                 --set grafana.adminPassword=${{ env.GRAFANA_ADMIN_PASSWORD }} \
                 --set prometheus.service.type=LoadBalancer \
                 --set grafana.service.type=LoadBalancer \
-                --set alertmanager.persistentVolume.storageClass="gp2",server.persistentVolume.storageClass="gp2" 
-              
-                # Wait for pods to be ready
-                timeout=300  # 5 minutes timeout
-                start_time=$(date +%s)
+                --set alertmanager.persistentVolume.storageClass="gp2" \
+                --set server.persistentVolume.storageClass="gp2" \
+                --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false \
+                --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false \
+                --set prometheus.prometheusSpec.resources.requests.cpu="200m" \
+                --set prometheus.prometheusSpec.resources.limits.cpu="1000m" \
+                --set prometheus.prometheusSpec.resources.requests.memory="200Mi" \
+                --set prometheus.prometheusSpec.resources.limits.memory="1Gi" \
+                --set grafana.resources.requests.cpu="100m" \
+                --set grafana.resources.limits.cpu="500m" \
+                --set grafana.resources.requests.memory="128Mi" \
+                --set grafana.resources.limits.memory="256Mi"
+                
+              # Wait for pods to be ready
+              echo "Waiting for pods to be ready..."
+              kubectl wait --for=condition=ready pod --all -n prometheus --timeout=300s
 
-                echo "Waiting for pods to be ready..."
-                while true; do
-                  if kubectl get pods -n prometheus -l "release=monitoring" | grep -q ContainerCreating; then
-                    echo "Some pods are still being created. Waiting..."
-                    sleep 10
-                  else
-                    echo "All pods are in Running state."
-                    break
-                  fi
+              echo "Checking final status of pods:"
+              kubectl get pods -n prometheus
 
-                  current_time=$(date +%s)
-                  if (( current_time - start_time > timeout )); then
-                    echo "Timeout reached. Some pods may not be ready."
-                    exit 1
-                  fi
-                done
+              # Configure Prometheus as a data source in Grafana
+              GRAFANA_POD=$(kubectl get pods -n prometheus -l "app.kubernetes.io/name=grafana" -o jsonpath="{.items[0].metadata.name}")
+              PROMETHEUS_SVC=$(kubectl get svc -n prometheus -l "app=kube-prometheus-stack-prometheus" -o jsonpath="{.items[0].metadata.name}")
 
-                echo "Checking final status of pods:"
-                kubectl get pods -n prometheus
-              
-                # Get deployment names
-                echo "Getting deployment names..."
-                GRAFANA_DEPLOYMENT=$(kubectl get deployments -n prometheus -l "app.kubernetes.io/name=grafana" -o jsonpath="{.items[0].metadata.name}")
-                PROMETHEUS_OPERATOR_DEPLOYMENT=$(kubectl get deployments -n prometheus -l "app.kubernetes.io/name=kube-prometheus-stack-operator" -o jsonpath="{.items[0].metadata.name}")
+              # Esperar un poco más para asegurarse de que Grafana esté completamente inicializado
+              sleep 30
 
-                # Get statefulset names
-                echo "Getting statefulset names..."
-                ALERTMANAGER_STATEFULSET=$(kubectl get statefulsets -n prometheus -l "app.kubernetes.io/name=alertmanager" -o jsonpath="{.items[0].metadata.name}")
-                PROMETHEUS_STATEFULSET=$(kubectl get statefulsets -n prometheus -l "app.kubernetes.io/name=prometheus" -o jsonpath="{.items[0].metadata.name}")
+              kubectl exec -n prometheus $GRAFANA_POD -- curl -X POST -H "Content-Type: application/json" -d "{\"name\":\"Prometheus\",\"type\":\"prometheus\",\"url\":\"http://$PROMETHEUS_SVC:9090\",\"access\":\"proxy\",\"isDefault\":true}" http://admin:${{ secrets.GRAFANA_ADMIN_PASSWORD }}@localhost:3000/api/datasources
+              '
 
-                # Wait for deployments
-                echo "Waiting for Grafana deployment: $GRAFANA_DEPLOYMENT"
-                kubectl wait --for=condition=available --timeout=300s deployment/$GRAFANA_DEPLOYMENT -n prometheus
-                echo "Waiting for Prometheus Operator deployment: $PROMETHEUS_OPERATOR_DEPLOYMENT"
-                kubectl wait --for=condition=available --timeout=300s deployment/$PROMETHEUS_OPERATOR_DEPLOYMENT -n prometheus
-
-                # Wait for statefulsets
-                echo "Waiting for Alertmanager statefulset: $ALERTMANAGER_STATEFULSET"
-                kubectl wait --for=condition=ready pod -l "app.kubernetes.io/name=alertmanager" --timeout=300s -n prometheus
-                echo "Waiting for Prometheus statefulset: $PROMETHEUS_STATEFULSET"
-                kubectl wait --for=condition=ready pod -l "app.kubernetes.io/name=prometheus" --timeout=300s -n prometheus
-
-                # Final check of all pods
-                echo "Final status of all pods in prometheus namespace:"
-                kubectl get pods -n prometheus
-                '
-
-    - name: Get Prometheus URL
-      id: prometheus-url
+    - name: Install jq
       run: |
-                  EC2_IP=${{ needs.Deploy_CloudFormation.outputs.ec2_ip }}
-                  PROMETHEUS_URL=$(ssh -i jenkins.pem -o StrictHostKeyChecking=no ubuntu@$EC2_IP '
-                  PROMETHEUS_SERVICE=$(kubectl get services -n prometheus -l "app.kubernetes.io/name=prometheus,app.kubernetes.io/instance=monitoring" -o jsonpath="{.items[0].metadata.name}")
-                  if [ -z "$PROMETHEUS_SERVICE" ]; then
-                    echo "Prometheus service not found. Listing all services in prometheus namespace:"
-                    kubectl get services -n prometheus
-                    exit 1
-                  fi
-                  kubectl get service $PROMETHEUS_SERVICE -n prometheus -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"
-                  ')
-                  if [ -z "$PROMETHEUS_URL" ]; then
-                    echo "Failed to get Prometheus URL"
-                    exit 1
-                  fi
-                  echo "prometheus_url=http://$PROMETHEUS_URL:9090" >> $GITHUB_OUTPUT
-      
+          EC2_IP=${{ needs.Deploy_CloudFormation.outputs.ec2_ip }}
+          ssh -i jenkins.pem -o StrictHostKeyChecking=no ubuntu@$EC2_IP 'sudo apt-get update && sudo apt-get install -y jq'
+          
     - name: Get Grafana URL
       id: grafana-url
       run: |
-                    EC2_IP=${{ needs.Deploy_CloudFormation.outputs.ec2_ip }}
-                    GRAFANA_URL=$(ssh -i jenkins.pem -o StrictHostKeyChecking=no ubuntu@$EC2_IP '
-                    GRAFANA_SERVICE=$(kubectl get services -n prometheus -l "app.kubernetes.io/name=grafana,app.kubernetes.io/instance=monitoring" -o jsonpath="{.items[0].metadata.name}")
-                    if [ -z "$GRAFANA_SERVICE" ]; then
-                      echo "Grafana service not found. Listing all services in prometheus namespace:"
-                      kubectl get services -n prometheus
-                      exit 1
-                    fi
-                    kubectl get service $GRAFANA_SERVICE -n prometheus -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"
-                    ')
-                    if [ -z "$GRAFANA_URL" ]; then
-                      echo "Failed to get Grafana URL"
-                      exit 1
-                    fi
-                    echo "grafana_url=http://$GRAFANA_URL" >> $GITHUB_OUTPUT
+            EC2_IP=${{ needs.Deploy_CloudFormation.outputs.ec2_ip }}
+            GRAFANA_URL=$(ssh -i jenkins.pem -o StrictHostKeyChecking=no ubuntu@$EC2_IP '
+            GRAFANA_SERVICE=$(kubectl get services -n prometheus -l "app.kubernetes.io/name=grafana" -o jsonpath="{.items[0].metadata.name}")
+            if [ -z "$GRAFANA_SERVICE" ]; then
+              echo "Grafana service not found."
+              exit 1
+            fi
+            echo "Found Grafana service: $GRAFANA_SERVICE"
+            kubectl get service $GRAFANA_SERVICE -n prometheus -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"
+            ')
+            if [ -z "$GRAFANA_URL" ]; then
+              echo "Failed to get Grafana URL"
+              exit 1
+            fi
+            echo "grafana_url=http://$GRAFANA_URL" >> $GITHUB_OUTPUT
 
   Create_Connection_Info:
     needs: [Deploy_CloudFormation, Deploy_Nginx, Deploy_EFK, Conexion_EC2, Deploy_Monitoring]
